apiVersion: v1
kind: Namespace
metadata:
  name: namespace1


---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: namespace1
spec:
  containers:
    - name: redis-pod
      image: redis
      ports:
      - containerPort: 9090
        name: http
        
